Fix stolonctl database restore command
gravitational/stolon pull request #27
Opened 2017-02-01 11:59 UTC by alexey-medvedchikov

1. Fixed fetching dump from S3
2. Fixed double restoration
3. Fixed restoration itself -- pg_restore was working like placebo (to stdout)

2017-02-01 14:17 UTC, UnderGreen requested changes

2017-02-01 14:17 UTC, UnderGreen commented on pkg/store/s3.go
> +	s3Object, err := client.GetObject(loc.Bucket, loc.Path)
I think, you can replace this code and io.Copy below with http://docs.minio.io/docs/golang-client-api-reference#FGetObject.

2017-02-02 05:58 UTC, agalitsyn commented on pkg/store/s3.go
> +	s3Object, err := client.GetObject(loc.Bucket, loc.Path)
sure, why not. It's more high level than GetObject, it wraps it and add additional checks for local FS, so use that

2017-02-02 05:58 UTC, agalitsyn approved these changes

2017-02-03 14:42 UTC, UnderGreen approved these changes

2017-02-03 14:48 UTC, merged